name: ServerLogger
version: 1.1
author: Pixel
main: it.pixel.serverlogger.ServerLogger
api-version: 1.18
commands:
  coords:
    description: This is a log(?)
    usage: /coords show
  log:
    description: This is a log(?)
    usage: /log show
  here:
    description: Show your current position to all players
    usage: /here
