name: ServerHandbook
version: 1.1
author: Pixel
main: it.pixel.serverhandbook.ServerHandbook
api-version: 1.18
commands:
  book:
    description: This is a log(?)
    usage: /coords <params>
  activity:
    description: This is a log(?)
    usage: /activity
  here:
    description: Show your current dimension to all players
    usage: /here
